create schema "ROOT"
CREATE TABLE IDENTITIES
    (IDENTITY_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
    CONSTRAINT IDENTITY_PK PRIMARY KEY, 
    uid VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    email_id VARCHAR(255)
    );
  