create schema "ROOT"
CREATE TABLE IDENTITIES
    (IDENTITY_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, 
    uid VARCHAR(255) NOT NULL PRIMARY KEY,
    display_name VARCHAR(255),
    email_id VARCHAR(255),
    password VARCHAR(255) NOT NULL
    );
  
    ALTER TABLE IDENTITIES ADD COLUMN password varchar(255);
   
  

DROP TABLE IDENTITIES;